name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pip install pytest
        pytest tests/
    
    - name: Create Release Package
      run: |
        chmod +x kubectl-ld
        chmod +x watch_rollout.py
        zip -r kubectl-ld-${{ github.ref_name }}.zip kubectl-ld watch_rollout.py mocks/ requirements.txt README.md LICENSE
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: kubectl-ld-${{ github.ref_name }}.zip
        generate_release_notes: true
        body: |
          ## kubectl-ld ${{ github.ref_name }}
          
          Mock CLI tool for debugging and simulating LLMInferenceService CRDs.
          
          ### Installation
          ```bash
          unzip kubectl-ld-${{ github.ref_name }}.zip
          pip install -r requirements.txt
          chmod +x kubectl-ld
          ./kubectl-ld help
          ```
          
          ### What's Changed
          See auto-generated release notes below.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}